### PR TITLE
Added f2-list.txt to xem-work

### PR DESCRIPTION
**Pull request by mrcmor100**

### CODE REVIEW

**Comment by pooser** [comment]
@mrcmor100 I think you intended to add this in the run-lists/hms/ directory, not in the top level 'run-lists' directory.

**Comment by pooser** [comment]
@mrcmor100 You need to delete the 'f2-list.txt' file that still remains in the 'run-list' directory.  The modification to the other file looks okay.

**Comment by pooser** [comment]
@mrcmor100 Did you ever address my previous comment?

**Comment by mrcmor100** [comment]
The extra f2-list in the upper directory should be removed.

**Pull request merged**
